### ISSUE TITLE
Add a JDS martrix class

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f24-SpMV#6]
## Description:
Add a JDS matrix class, which is a child class of the SparseMatrix class.

**Amendment by @S-A-Almohri** 
The primary goal of this issue is to create a new class JDSMatrix as a child class of SparseMatrix to support efficient sparse matrix-vector multiplication (SpMV). This class will provide constructors for initializing the matrix and methods necessary for performing efficient SpMV. Integration with existing matrix operations in the SparseMatrix superclass is essential. Detailed documentation and usage examples for the two main methods (viewing and multiplication) will be provided to assist the tester. The class will assume that the input matrix is read in Coordinate (COO) format.

## Tasks:

**Added by @S-A-Almohri** 
**Design the JDSMatrix Class:**
- Define the structure of the JDSMatrix class.
- Include member variables specific to JDS storage format, such as arrays for row indices, column indices, and non-zero values.
- Ensure it adheres to the interface set by SparseMatrix.

**Implement Constructors:**
- Default constructor that initializes an empty JDS matrix.
- Parameterized constructor that takes arguments for each member variable and sets up the matrix for SpMV.

**Implement Core Methods:**
- Method for setting matrix elements (overriding setCoefficient if necessary).
- Implement an efficient algorithm for SpMV:
   SpMV method: std::vector<fp_type> multiply(const std::vector<fp_type>& vec) const;
- Method for viewing matrix elements:
   View method: void display() const;

**Integrate with SparseMatrix:**
- Ensure JDSMatrix correctly overrides and/or extends methods in SparseMatrix.
- Maintain compatibility with existing matrix operations in the superclass.

## Definition of done:
Must include a [default constructor](https://en.cppreference.com/w/cpp/language/default_constructor) and a constructor which takes one argument per member variable and directly assembles the class.

**Amendment by @S-A-Almohri**
- A JDSMatrix class exists and extends SparseMatrix.
- The class includes a default constructor and a parameterized constructor for member variables. (from Kyle)
- An efficient method for SpMV is implemented.
- A method for viewing matrix elements is implemented.
- The code is ready to be reviewed by a tester and integrates smoothly into the existing codebase.

**Comment by bjorngkierulf** [comment]
I'm reviewing this. The issue looks good, though you could clarify that for this issue, you don't need full implementations of all the methods you listed like view and matrix vector multiply.

**Comment by S-A-Almohri** [comment]
@bjorngkierulf Ready for review

**Comment by bjorngkierulf** [comment]
@S-A-Almohri Sorry for the delay, overall, this looks good. Here are my thoughts:
 
For the variable names - personally, I would try to find more intuitive variable names, mostly for perm and jd_ptr. That said, those are the names in the Lec13 UML, so I'll leave it up to you if you change these.
 
For the parametrized constructor - I guess this is fine, but I don't see the use case where a user would want to use this. You could probably keep this as is, if you can also add a parametrized constructor that only takes nrows and ncols, because I think that's the more common use case.
 
For the matvec: The interface you have now should work, but we should try to standardize the interface across child classes. Eg. for COO, matvec takes a std::vector and returns a std::vector. Either way is fine, but we should discuss and standardize, so that the (hypothetical) user doesn't need to use a different interface based on the matrix's storage format.
 
For the destructor - I think the std::vector's should destroy themselves automatically, but I don't think max_nz_row will.
 
But overall I think this is good. I haven't tried compiling this so I don't know if there are any errors there.

**Comment by S-A-Almohri** [comment]
Good points but since dependent codes are compiling I think we shouldn't change it; I left that for the matvec implementer, the code is not compiling because of an error in matvec for now after that got implemented by the implementor (I think his loop ordering could be wrong but that's a different unrelated issue)

**Comment by bjorngkierulf** [comment]
That's great! Sorry for the late response. I guess there's no pull request but I think this issue is done, so I'll close it out.
